# OpenAPI Python Client Configuration

# Package and project naming
package_name_override: "openapi_client"
project_name_override: "tofupilot"

# Class naming
use_path_prefixes_for_title_model_names: false

# Documentation
docstrings_on_attributes: true

# Enum handling
literal_enums: false

# Tag generation
generate_all_tags: true

# Field naming
field_prefix: "field_"

# Network settings
http_timeout: 60

# Overrides
class_overrides:
  RunCreateBody:
    class_name: Run
    module_name: run
  RunCreateBodyOutcome:
    class_name: RunOutcome
    module_name: run_outcome

content_type_overrides: {}

# Post-generation hooks (use Ruff for formatting)
post_hooks:
  - "ruff check . --fix"
  - "ruff format ."