"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from typing_extensions import TypedDict


class BatchCreateRequestTypedDict(TypedDict):
    number: str
    r"""The batch number identifier"""


class BatchCreateRequest(BaseModel):
    number: str
    r"""The batch number identifier"""


class BatchCreateResponseTypedDict(TypedDict):
    r"""Batch created successfully"""

    id: str
    r"""Unique identifier for the created batch"""


class BatchCreateResponse(BaseModel):
    r"""Batch created successfully"""

    id: str
    r"""Unique identifier for the created batch"""
