"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class BatchUpdateRequestBodyTypedDict(TypedDict):
    new_number: str
    r"""New batch number."""


class BatchUpdateRequestBody(BaseModel):
    new_number: str
    r"""New batch number."""


class BatchUpdateRequestTypedDict(TypedDict):
    number: str
    r"""Current batch number to update."""
    request_body: BatchUpdateRequestBodyTypedDict


class BatchUpdateRequest(BaseModel):
    number: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Current batch number to update."""

    request_body: Annotated[
        BatchUpdateRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class BatchUpdateResponseTypedDict(TypedDict):
    r"""Batch updated successfully"""

    id: str
    r"""Unique identifier of the updated batch."""


class BatchUpdateResponse(BaseModel):
    r"""Batch updated successfully"""

    id: str
    r"""Unique identifier of the updated batch."""
