"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class BatchDeleteRequestTypedDict(TypedDict):
    number: str


class BatchDeleteRequest(BaseModel):
    number: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class BatchDeleteResponseTypedDict(TypedDict):
    r"""Response for successful batch deletion"""

    id: str
    r"""ID of the successfully deleted batch"""


class BatchDeleteResponse(BaseModel):
    r"""Response for successful batch deletion"""

    id: str
    r"""ID of the successfully deleted batch"""
