"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from typing_extensions import TypedDict


class ErrorPRECONDITIONFAILEDIssueTypedDict(TypedDict):
    message: str


class ErrorPRECONDITIONFAILEDIssue(BaseModel):
    message: str
