"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from tofupilot.v2.types import BaseModel
from typing_extensions import TypedDict


class GithubGetInstallationTokenResponseTypedDict(TypedDict):
    r"""Token and expiration time, or null if no GitHub App is installed for the organization"""

    token: str
    r"""GitHub installation access token"""
    expires_at: datetime
    r"""Token expiration time in ISO 8601 format"""


class GithubGetInstallationTokenResponse(BaseModel):
    r"""Token and expiration time, or null if no GitHub App is installed for the organization"""

    token: str
    r"""GitHub installation access token"""

    expires_at: datetime
    r"""Token expiration time in ISO 8601 format"""
