"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class PartDeleteRevisionRequestTypedDict(TypedDict):
    part_number: str
    r"""Part number that the revision belongs to."""
    revision_number: str
    r"""Revision number to delete."""


class PartDeleteRevisionRequest(BaseModel):
    part_number: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Part number that the revision belongs to."""

    revision_number: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Revision number to delete."""


class PartDeleteRevisionResponseTypedDict(TypedDict):
    r"""Revision deleted successfully"""

    id: str
    r"""Unique identifier of the deleted revision."""


class PartDeleteRevisionResponse(BaseModel):
    r"""Revision deleted successfully"""

    id: str
    r"""Unique identifier of the deleted revision."""
