"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


PartCreateRevisionMetadataTypedDict = TypeAliasType(
    "PartCreateRevisionMetadataTypedDict", Union[str, float, bool]
)


PartCreateRevisionMetadata = TypeAliasType(
    "PartCreateRevisionMetadata", Union[str, float, bool]
)


class PartCreateRevisionRequestBodyTypedDict(TypedDict):
    number: str
    r"""Revision number (e.g., version number or code)."""
    metadata: NotRequired[Dict[str, PartCreateRevisionMetadataTypedDict]]
    r"""Custom metadata to attach to the revision (max 50 keys per revision). Plain object of key/value pairs; values can be string, number, or boolean. Type is detected from the value."""


class PartCreateRevisionRequestBody(BaseModel):
    number: str
    r"""Revision number (e.g., version number or code)."""

    metadata: Optional[Dict[str, PartCreateRevisionMetadata]] = None
    r"""Custom metadata to attach to the revision (max 50 keys per revision). Plain object of key/value pairs; values can be string, number, or boolean. Type is detected from the value."""


class PartCreateRevisionRequestTypedDict(TypedDict):
    part_number: str
    r"""Part number to create a revision for."""
    request_body: PartCreateRevisionRequestBodyTypedDict


class PartCreateRevisionRequest(BaseModel):
    part_number: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Part number to create a revision for."""

    request_body: Annotated[
        PartCreateRevisionRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class PartCreateRevisionResponseTypedDict(TypedDict):
    r"""Revision created successfully"""

    id: str
    r"""Unique identifier of the created revision."""


class PartCreateRevisionResponse(BaseModel):
    r"""Revision created successfully"""

    id: str
    r"""Unique identifier of the created revision."""
