"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class ProcedureDeleteRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the procedure to delete."""


class ProcedureDeleteRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the procedure to delete."""


class ProcedureDeleteResponseTypedDict(TypedDict):
    r"""Procedure deleted successfully"""

    id: str
    r"""Unique identifier of the deleted procedure."""


class ProcedureDeleteResponse(BaseModel):
    r"""Procedure deleted successfully"""

    id: str
    r"""Unique identifier of the deleted procedure."""
