"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, QueryParamMetadata
from typing import List
from typing_extensions import Annotated, TypedDict


class RunDeleteRequestTypedDict(TypedDict):
    ids: List[str]
    r"""Array of run IDs to delete."""


class RunDeleteRequest(BaseModel):
    ids: Annotated[
        List[str], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Array of run IDs to delete."""


class RunDeleteResponseTypedDict(TypedDict):
    r"""Response for successful run deletion"""

    ids: List[str]
    r"""Array of IDs of the runs that were successfully deleted"""


class RunDeleteResponse(BaseModel):
    r"""Response for successful run deletion"""

    ids: List[str]
    r"""Array of IDs of the runs that were successfully deleted"""
