"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from tofupilot.v2.types import BaseModel, UNSET_SENTINEL
from tofupilot.v2.utils import FieldMetadata, QueryParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RunDeleteRequestTypedDict(TypedDict):
    ids: NotRequired[List[str]]


class RunDeleteRequest(BaseModel):
    ids: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RunDeleteResponseTypedDict(TypedDict):
    r"""Response for successful run deletion"""

    ids: List[str]
    r"""Array of IDs of the runs that were successfully deleted"""


class RunDeleteResponse(BaseModel):
    r"""Response for successful run deletion"""

    ids: List[str]
    r"""Array of IDs of the runs that were successfully deleted"""
