"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from tofupilot.v2.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


StationUpdateImageIDEnum = Literal[""]

StationUpdateImageIDUnionTypedDict = TypeAliasType(
    "StationUpdateImageIDUnionTypedDict", Union[str, StationUpdateImageIDEnum]
)
r"""Upload ID for the station image, or empty string to remove image"""


StationUpdateImageIDUnion = TypeAliasType(
    "StationUpdateImageIDUnion", Union[str, StationUpdateImageIDEnum]
)
r"""Upload ID for the station image, or empty string to remove image"""


class StationUpdateRequestBodyTypedDict(TypedDict):
    name: NotRequired[str]
    r"""New name for the station"""
    image_id: NotRequired[StationUpdateImageIDUnionTypedDict]
    r"""Upload ID for the station image, or empty string to remove image"""
    team_id: NotRequired[Nullable[str]]
    r"""Team ID to assign this station to, or null to unassign"""


class StationUpdateRequestBody(BaseModel):
    name: Optional[str] = None
    r"""New name for the station"""

    image_id: Optional[StationUpdateImageIDUnion] = None
    r"""Upload ID for the station image, or empty string to remove image"""

    team_id: OptionalNullable[str] = UNSET
    r"""Team ID to assign this station to, or null to unassign"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["name", "image_id", "team_id"]
        nullable_fields = ["team_id"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class StationUpdateRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the station to update"""
    request_body: StationUpdateRequestBodyTypedDict


class StationUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the station to update"""

    request_body: Annotated[
        StationUpdateRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class StationUpdateResponseTypedDict(TypedDict):
    r"""Station updated successfully"""

    id: str
    r"""Unique identifier of the updated station"""
    name: str
    r"""Name of the station"""


class StationUpdateResponse(BaseModel):
    r"""Station updated successfully"""

    id: str
    r"""Unique identifier of the updated station"""

    name: str
    r"""Name of the station"""
