"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from tofupilot.v2.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class StationCreateRequestTypedDict(TypedDict):
    name: str
    r"""Name of the station"""
    procedure_id: NotRequired[str]
    r"""Optional procedure ID to link the station to"""


class StationCreateRequest(BaseModel):
    name: str
    r"""Name of the station"""

    procedure_id: Optional[str] = None
    r"""Optional procedure ID to link the station to"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["procedure_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StationCreateResponseTypedDict(TypedDict):
    r"""Station created successfully"""

    id: str
    r"""Unique identifier of the created station"""


class StationCreateResponse(BaseModel):
    r"""Station created successfully"""

    id: str
    r"""Unique identifier of the created station"""
