"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from datetime import datetime
from tofupilot.v2 import errors, models, utils
from tofupilot.v2._hooks import HookContext
from tofupilot.v2.types import OptionalNullable, UNSET
from tofupilot.v2.utils import get_security_from_env
from tofupilot.v2.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, List, Mapping, Optional


class MeasurementsSDK(BaseSDK):
    def list(
        self,
        *,
        procedure_id: str,
        phase_name: Optional[str] = None,
        measurement_name: Optional[str] = None,
        phase_names: Optional[List[str]] = None,
        outcomes: Optional[List[models.MeasurementListQueryParamOutcome]] = None,
        ids: Optional[List[str]] = None,
        duration_min: Optional[str] = None,
        duration_max: Optional[str] = None,
        deployment_ids: Optional[List[str]] = None,
        procedure_versions: Optional[List[str]] = None,
        environments: Optional[List[models.MeasurementListEnvironment]] = None,
        serial_numbers: Optional[List[str]] = None,
        part_numbers: Optional[List[str]] = None,
        revision_numbers: Optional[List[str]] = None,
        batch_numbers: Optional[List[str]] = None,
        operated_by_ids: Optional[List[str]] = None,
        created_by_station_ids: Optional[List[str]] = None,
        created_by_user_ids: Optional[List[str]] = None,
        started_after: Optional[datetime] = None,
        started_before: Optional[datetime] = None,
        exclude_retries: Optional[bool] = True,
        value_min: Optional[float] = None,
        value_max: Optional[float] = None,
        value_bool: Optional[bool] = None,
        value_strings: Optional[List[str]] = None,
        measurement_outcomes: Optional[
            List[models.QueryParamMeasurementOutcome]
        ] = None,
        measurement_types: Optional[List[models.QueryParamMeasurementType]] = None,
        sort_by: Optional[models.MeasurementListSortBy] = "started_at",
        sort_order: Optional[models.MeasurementListSortOrder] = "desc",
        limit: Optional[int] = 50,
        cursor: Optional[int] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.MeasurementListResponse:
        r"""List and filter measurements

        List measurements for a procedure with filtering by phase, measurement, value, outcome, date range, unit, and run details. Cursor-paginated.

        :param procedure_id: Procedure to list measurements for. Required: measurements are scoped to a single procedure.
        :param phase_name:
        :param measurement_name:
        :param phase_names:
        :param outcomes:
        :param ids:
        :param duration_min:
        :param duration_max:
        :param deployment_ids:
        :param procedure_versions:
        :param environments:
        :param serial_numbers:
        :param part_numbers:
        :param revision_numbers:
        :param batch_numbers:
        :param operated_by_ids:
        :param created_by_station_ids:
        :param created_by_user_ids:
        :param started_after:
        :param started_before:
        :param exclude_retries: Exclude retried phase attempts, keeping only the final attempt.
        :param value_min:
        :param value_max:
        :param value_bool:
        :param value_strings:
        :param measurement_outcomes:
        :param measurement_types:
        :param sort_by: Field to sort results by.
        :param sort_order: Sort order direction.
        :param limit: Maximum number of measurements to return.
        :param cursor: Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.MeasurementListRequest(
            procedure_id=procedure_id,
            phase_name=phase_name,
            measurement_name=measurement_name,
            phase_names=phase_names,
            outcomes=outcomes,
            ids=ids,
            duration_min=duration_min,
            duration_max=duration_max,
            deployment_ids=deployment_ids,
            procedure_versions=procedure_versions,
            environments=environments,
            serial_numbers=serial_numbers,
            part_numbers=part_numbers,
            revision_numbers=revision_numbers,
            batch_numbers=batch_numbers,
            operated_by_ids=operated_by_ids,
            created_by_station_ids=created_by_station_ids,
            created_by_user_ids=created_by_user_ids,
            started_after=started_after,
            started_before=started_before,
            exclude_retries=exclude_retries,
            value_min=value_min,
            value_max=value_max,
            value_bool=value_bool,
            value_strings=value_strings,
            measurement_outcomes=measurement_outcomes,
            measurement_types=measurement_types,
            sort_by=sort_by,
            sort_order=sort_order,
            limit=limit,
            cursor=cursor,
        )

        req = self._build_request(
            method="GET",
            path="/v2/measurements",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="measurement-list",
                oauth2_scopes=[],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.MeasurementListResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorBADREQUESTData, http_res
            )
            raise errors.ErrorBADREQUEST(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorUNAUTHORIZEDData, http_res
            )
            raise errors.ErrorUNAUTHORIZED(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorINTERNALSERVERERRORData, http_res
            )
            raise errors.ErrorINTERNALSERVERERROR(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def list_async(
        self,
        *,
        procedure_id: str,
        phase_name: Optional[str] = None,
        measurement_name: Optional[str] = None,
        phase_names: Optional[List[str]] = None,
        outcomes: Optional[List[models.MeasurementListQueryParamOutcome]] = None,
        ids: Optional[List[str]] = None,
        duration_min: Optional[str] = None,
        duration_max: Optional[str] = None,
        deployment_ids: Optional[List[str]] = None,
        procedure_versions: Optional[List[str]] = None,
        environments: Optional[List[models.MeasurementListEnvironment]] = None,
        serial_numbers: Optional[List[str]] = None,
        part_numbers: Optional[List[str]] = None,
        revision_numbers: Optional[List[str]] = None,
        batch_numbers: Optional[List[str]] = None,
        operated_by_ids: Optional[List[str]] = None,
        created_by_station_ids: Optional[List[str]] = None,
        created_by_user_ids: Optional[List[str]] = None,
        started_after: Optional[datetime] = None,
        started_before: Optional[datetime] = None,
        exclude_retries: Optional[bool] = True,
        value_min: Optional[float] = None,
        value_max: Optional[float] = None,
        value_bool: Optional[bool] = None,
        value_strings: Optional[List[str]] = None,
        measurement_outcomes: Optional[
            List[models.QueryParamMeasurementOutcome]
        ] = None,
        measurement_types: Optional[List[models.QueryParamMeasurementType]] = None,
        sort_by: Optional[models.MeasurementListSortBy] = "started_at",
        sort_order: Optional[models.MeasurementListSortOrder] = "desc",
        limit: Optional[int] = 50,
        cursor: Optional[int] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.MeasurementListResponse:
        r"""List and filter measurements

        List measurements for a procedure with filtering by phase, measurement, value, outcome, date range, unit, and run details. Cursor-paginated.

        :param procedure_id: Procedure to list measurements for. Required: measurements are scoped to a single procedure.
        :param phase_name:
        :param measurement_name:
        :param phase_names:
        :param outcomes:
        :param ids:
        :param duration_min:
        :param duration_max:
        :param deployment_ids:
        :param procedure_versions:
        :param environments:
        :param serial_numbers:
        :param part_numbers:
        :param revision_numbers:
        :param batch_numbers:
        :param operated_by_ids:
        :param created_by_station_ids:
        :param created_by_user_ids:
        :param started_after:
        :param started_before:
        :param exclude_retries: Exclude retried phase attempts, keeping only the final attempt.
        :param value_min:
        :param value_max:
        :param value_bool:
        :param value_strings:
        :param measurement_outcomes:
        :param measurement_types:
        :param sort_by: Field to sort results by.
        :param sort_order: Sort order direction.
        :param limit: Maximum number of measurements to return.
        :param cursor: Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.MeasurementListRequest(
            procedure_id=procedure_id,
            phase_name=phase_name,
            measurement_name=measurement_name,
            phase_names=phase_names,
            outcomes=outcomes,
            ids=ids,
            duration_min=duration_min,
            duration_max=duration_max,
            deployment_ids=deployment_ids,
            procedure_versions=procedure_versions,
            environments=environments,
            serial_numbers=serial_numbers,
            part_numbers=part_numbers,
            revision_numbers=revision_numbers,
            batch_numbers=batch_numbers,
            operated_by_ids=operated_by_ids,
            created_by_station_ids=created_by_station_ids,
            created_by_user_ids=created_by_user_ids,
            started_after=started_after,
            started_before=started_before,
            exclude_retries=exclude_retries,
            value_min=value_min,
            value_max=value_max,
            value_bool=value_bool,
            value_strings=value_strings,
            measurement_outcomes=measurement_outcomes,
            measurement_types=measurement_types,
            sort_by=sort_by,
            sort_order=sort_order,
            limit=limit,
            cursor=cursor,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/measurements",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="measurement-list",
                oauth2_scopes=[],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.MeasurementListResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorBADREQUESTData, http_res
            )
            raise errors.ErrorBADREQUEST(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorUNAUTHORIZEDData, http_res
            )
            raise errors.ErrorUNAUTHORIZED(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorINTERNALSERVERERRORData, http_res
            )
            raise errors.ErrorINTERNALSERVERERROR(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def get(
        self,
        *,
        id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.MeasurementGetResponse:
        r"""Get measurement

        Get a single measurement by ID, with its value, validators, and run context.

        :param id: ID of the measurement to retrieve.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.MeasurementGetRequest(
            id=id,
        )

        req = self._build_request(
            method="GET",
            path="/v2/measurements/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="measurement-get",
                oauth2_scopes=[],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.MeasurementGetResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorUNAUTHORIZEDData, http_res
            )
            raise errors.ErrorUNAUTHORIZED(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorNOTFOUNDData, http_res)
            raise errors.ErrorNOTFOUND(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorINTERNALSERVERERRORData, http_res
            )
            raise errors.ErrorINTERNALSERVERERROR(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def get_async(
        self,
        *,
        id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.MeasurementGetResponse:
        r"""Get measurement

        Get a single measurement by ID, with its value, validators, and run context.

        :param id: ID of the measurement to retrieve.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.MeasurementGetRequest(
            id=id,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/measurements/{id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="measurement-get",
                oauth2_scopes=[],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.MeasurementGetResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorUNAUTHORIZEDData, http_res
            )
            raise errors.ErrorUNAUTHORIZED(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorNOTFOUNDData, http_res)
            raise errors.ErrorNOTFOUND(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.ErrorINTERNALSERVERERRORData, http_res
            )
            raise errors.ErrorINTERNALSERVERERROR(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)
