"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import attachment_deleteop as models_attachment_deleteop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class AttachmentDeleteInternalServerErrorError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[
        List[models_attachment_deleteop.AttachmentDeleteInternalServerErrorIssue]
    ] = None
    r"""An array of issues that were responsible for the error"""


class AttachmentDeleteInternalServerErrorError500(TofuPilotError):
    r"""The error information"""

    data: AttachmentDeleteInternalServerErrorError500Data

    def __init__(
        self,
        data: AttachmentDeleteInternalServerErrorError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class NoUploadsFoundWithKeysS3KeysError404Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_attachment_deleteop.AttachmentDeleteNotFoundIssue]] = (
        None
    )
    r"""An array of issues that were responsible for the error"""


class NoUploadsFoundWithKeysS3KeysError404(TofuPilotError):
    r"""The error information"""

    data: NoUploadsFoundWithKeysS3KeysError404Data

    def __init__(
        self,
        data: NoUploadsFoundWithKeysS3KeysError404Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
