"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import batch_createop as models_batch_createop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class BatchCreateInternalServerErrorError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[
        List[models_batch_createop.BatchCreateInternalServerErrorIssue]
    ] = None
    r"""An array of issues that were responsible for the error"""


class BatchCreateInternalServerErrorError500(TofuPilotError):
    r"""The error information"""

    data: BatchCreateInternalServerErrorError500Data

    def __init__(
        self,
        data: BatchCreateInternalServerErrorError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class ABatchWithThisNumberAlreadyExistsInTheOrganizationError409Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_batch_createop.BatchCreateConflictIssue]] = None
    r"""An array of issues that were responsible for the error"""


class ABatchWithThisNumberAlreadyExistsInTheOrganizationError409(TofuPilotError):
    r"""The error information"""

    data: ABatchWithThisNumberAlreadyExistsInTheOrganizationError409Data

    def __init__(
        self,
        data: ABatchWithThisNumberAlreadyExistsInTheOrganizationError409Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class BatchNumberCanOnlyContainLettersNumbersUnderscoresAndDashesError400Data(
    BaseModel
):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_batch_createop.BatchCreateBadRequestIssue]] = None
    r"""An array of issues that were responsible for the error"""


class BatchNumberCanOnlyContainLettersNumbersUnderscoresAndDashesError400(
    TofuPilotError
):
    r"""The error information"""

    data: BatchNumberCanOnlyContainLettersNumbersUnderscoresAndDashesError400Data

    def __init__(
        self,
        data: BatchNumberCanOnlyContainLettersNumbersUnderscoresAndDashesError400Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
