"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import errorforbidden as models_errorforbidden
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class ErrorFORBIDDENData(BaseModel):
    message: str
    r"""The error message"""
    code: str
    r"""The error code"""
    issues: Optional[List[models_errorforbidden.ErrorFORBIDDENIssue]] = None
    r"""An array of issues that were responsible for the error"""


@dataclass(unsafe_hash=True)
class ErrorFORBIDDEN(TofuPilotError):
    r"""Forbidden error"""

    data: ErrorFORBIDDENData = field(hash=False)

    def __init__(
        self,
        data: ErrorFORBIDDENData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
