"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import (
    github_getinstallationtokenop as models_github_getinstallationtokenop,
)
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class GITHUBINSTALLATIONSUSPENDEDError412Data(BaseModel):
    message: str
    r"""The error message"""
    code: str
    r"""The error code"""
    issues: Optional[
        List[models_github_getinstallationtokenop.GithubGetInstallationTokenIssue]
    ] = None
    r"""An array of issues that were responsible for the error"""


@dataclass(unsafe_hash=True)
class GITHUBINSTALLATIONSUSPENDEDError412(TofuPilotError):
    r"""The error information"""

    data: GITHUBINSTALLATIONSUSPENDEDError412Data = field(hash=False)

    def __init__(
        self,
        data: GITHUBINSTALLATIONSUSPENDEDError412Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
