"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import part_getop as models_part_getop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class PartGetInternalServerErrorError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_part_getop.PartGetInternalServerErrorIssue]] = None
    r"""An array of issues that were responsible for the error"""


class PartGetInternalServerErrorError500(TofuPilotError):
    r"""The error information"""

    data: PartGetInternalServerErrorError500Data

    def __init__(
        self,
        data: PartGetInternalServerErrorError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class PartNotFoundNumberError404Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_part_getop.PartGetNotFoundIssue]] = None
    r"""An array of issues that were responsible for the error"""


class PartNotFoundNumberError404(TofuPilotError):
    r"""The error information"""

    data: PartNotFoundNumberError404Data

    def __init__(
        self,
        data: PartNotFoundNumberError404Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
