"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import part_deleterevisionop as models_part_deleterevisionop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class PartDeleteRevisionInternalServerErrorError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[
        List[models_part_deleterevisionop.PartDeleteRevisionInternalServerErrorIssue]
    ] = None
    r"""An array of issues that were responsible for the error"""


class PartDeleteRevisionInternalServerErrorError500(TofuPilotError):
    r"""The error information"""

    data: PartDeleteRevisionInternalServerErrorError500Data

    def __init__(
        self,
        data: PartDeleteRevisionInternalServerErrorError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class PartDeleteRevisionRevisionRevisionNumberNotFoundForPartPartNumberError404Data(
    BaseModel
):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[
        List[models_part_deleterevisionop.PartDeleteRevisionNotFoundIssue]
    ] = None
    r"""An array of issues that were responsible for the error"""


class PartDeleteRevisionRevisionRevisionNumberNotFoundForPartPartNumberError404(
    TofuPilotError
):
    r"""The error information"""

    data: PartDeleteRevisionRevisionRevisionNumberNotFoundForPartPartNumberError404Data

    def __init__(
        self,
        data: PartDeleteRevisionRevisionRevisionNumberNotFoundForPartPartNumberError404Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
