"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import procedure_deleteop as models_procedure_deleteop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class InternalServerErrorFailedToDeleteProcedureErrorError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[
        List[models_procedure_deleteop.ProcedureDeleteInternalServerErrorIssue]
    ] = None
    r"""An array of issues that were responsible for the error"""


class InternalServerErrorFailedToDeleteProcedureErrorError500(TofuPilotError):
    r"""The error information"""

    data: InternalServerErrorFailedToDeleteProcedureErrorError500Data

    def __init__(
        self,
        data: InternalServerErrorFailedToDeleteProcedureErrorError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class ProcedureDeleteProcedureWithIDIDNotFoundError404Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_procedure_deleteop.ProcedureDeleteNotFoundIssue]] = (
        None
    )
    r"""An array of issues that were responsible for the error"""


class ProcedureDeleteProcedureWithIDIDNotFoundError404(TofuPilotError):
    r"""The error information"""

    data: ProcedureDeleteProcedureWithIDIDNotFoundError404Data

    def __init__(
        self,
        data: ProcedureDeleteProcedureWithIDIDNotFoundError404Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
