"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import run_listop as models_run_listop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class RunListInternalServerErrorMessageError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_run_listop.RunListIssue]] = None
    r"""An array of issues that were responsible for the error"""


class RunListInternalServerErrorMessageError500(TofuPilotError):
    r"""The error information"""

    data: RunListInternalServerErrorMessageError500Data

    def __init__(
        self,
        data: RunListInternalServerErrorMessageError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
