"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import run_deleteop as models_run_deleteop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class RunDeleteInternalServerErrorError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_run_deleteop.RunDeleteInternalServerErrorIssue]] = None
    r"""An array of issues that were responsible for the error"""


class RunDeleteInternalServerErrorError500(TofuPilotError):
    r"""The error information"""

    data: RunDeleteInternalServerErrorError500Data

    def __init__(
        self,
        data: RunDeleteInternalServerErrorError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class NoRunsFoundWithIDsRunIdsError404Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_run_deleteop.RunDeleteNotFoundIssue]] = None
    r"""An array of issues that were responsible for the error"""


class NoRunsFoundWithIDsRunIdsError404(TofuPilotError):
    r"""The error information"""

    data: NoRunsFoundWithIDsRunIdsError404Data

    def __init__(
        self,
        data: NoRunsFoundWithIDsRunIdsError404Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
