"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import unit_deleteop as models_unit_deleteop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class UnitDeleteInternalServerErrorError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_unit_deleteop.UnitDeleteInternalServerErrorIssue]] = (
        None
    )
    r"""An array of issues that were responsible for the error"""


class UnitDeleteInternalServerErrorError500(TofuPilotError):
    r"""The error information"""

    data: UnitDeleteInternalServerErrorError500Data

    def __init__(
        self,
        data: UnitDeleteInternalServerErrorError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class NoUnitsFoundWithSerialNumbersSerialNumbersError404Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_unit_deleteop.UnitDeleteNotFoundIssue]] = None
    r"""An array of issues that were responsible for the error"""


class NoUnitsFoundWithSerialNumbersSerialNumbersError404(TofuPilotError):
    r"""The error information"""

    data: NoUnitsFoundWithSerialNumbersSerialNumbersError404Data

    def __init__(
        self,
        data: NoUnitsFoundWithSerialNumbersSerialNumbersError404Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
