"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from tofupilot.v2.errors import TofuPilotError
from tofupilot.v2.models import unit_getop as models_unit_getop
from tofupilot.v2.types import BaseModel
from typing import List, Optional


class UnitGetInternalServerErrorMessageError500Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_unit_getop.UnitGetInternalServerErrorIssue]] = None
    r"""An array of issues that were responsible for the error"""


class UnitGetInternalServerErrorMessageError500(TofuPilotError):
    r"""The error information"""

    data: UnitGetInternalServerErrorMessageError500Data

    def __init__(
        self,
        data: UnitGetInternalServerErrorMessageError500Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data


class UnitNotFoundSerialNumberError404Data(BaseModel):
    message: str
    r"""The error message"""

    code: str
    r"""The error code"""

    issues: Optional[List[models_unit_getop.UnitGetNotFoundIssue]] = None
    r"""An array of issues that were responsible for the error"""


class UnitNotFoundSerialNumberError404(TofuPilotError):
    r"""The error information"""

    data: UnitNotFoundSerialNumberError404Data

    def __init__(
        self,
        data: UnitNotFoundSerialNumberError404Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
